---

language: python
python: "2.7"
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - echo localhost > inventory
env:
  - IMAGE_BUILD_PLATFORM=centos:7 INIT=/usr/sbin/init
  - IMAGE_BUILD_PLATFORM=opensuse:42.1 INIT=/sbin/systemd
  - IMAGE_BUILD_PLATFORM=centos:6 INIT=/usr/sbin/init
  - IMAGE_BUILD_PLATFORM=debian:jessie INIT=/sbin/systemd
  - IMAGE_BUILD_PLATFORM=ubuntu:trusty INIT=/usr/sbin/init
install:
  - pip install ansible==1.9.4
before_script:
  # Syntax check, dont't bother if this fails...
  - ansible-playbook -i inventory tests/test.yml --syntax-check

script:
  - docker run --privileged -e "container=docker"  -v /sys/fs/cgroup:/sys/fs/cgroup $IMAGE_BUILD_PLATFORM $INIT
  - DOCKER_ID=$(docker ps |sed -e '/$IMAGE_BUILD_PLATFORM/!d;s/ .*//g')
