# file: mysql/tasks/install.yml

- name: MySQL | Load the os specific variables
  include_vars: "{{ansible_os_family | lower}}.yml"
  when: mysql_packages is not defined

- name: MySQL | Add APT repository
  apt_repository: repo={{mysql_ppa}} update_cache=yes
  when: mysql_ppa != False and mysql_ppa != ""

- name: MySQL | Make sure the MySQL packages are installed
  apt:
    pkg: "{{item}}"
    update_cache: yes
  with_items: mysql_packages

- name: MySQL | Ensure MySQL is running
  service:
    name: mysql
    state: started
