# file: mysql/tasks/install.yml

- name: MySQL | Add APT repository
  apt_repository: repo={{mysql_ppa}} update_cache=yes
  when: ( mysql_repository != False and mysql_repository != "" ) and ( "{{ansible_os_family | lower}}" == "ubuntu" or "{{ansible_os_family | lower}}" == "debian")

- name: MySQL | Make sure the MySQL packages are installed debian/ubuntu
  apt:
    pkg: "{{item}}"
    update_cache: yes
  with_items:  "{{ mysql_packages[ ansible_os_family |lower ] }}"
  when: '"{{ansible_os_family | lower}}" == "ubuntu" or "{{ansible_os_family | lower}}" == "debian"'

###### Unfortunatelly this does not work on ansible < 2.x so for now commented...
#- name: Add mariadb repository
#  yumrepo:
#    name: mariadb
#    description: MariaDB package repsitory 
#    file: mariadb
#    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
#    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
#    gpgcheck: yes
#    enabled: yes
#  when: '"{{ansible_os_family | lower}}" == "redhat"'

- name: MySQL | Make sure the MySQL packages are installed RedHat/CentOS
  yum:
    pkg: "{{item}}"
    update_cache: yes
  with_items: "{{ mysql_packages[ ansible_os_family |lower ] }}"
  when: '"{{ansible_os_family | lower}}" == "redhat"'

- name: MySQL | Make sure the MySQL packages are installed openSUSE
  zypper:
    name: "{{item}}"
    state: present
  with_items: "{{ mysql_packages[ ansible_os_family |lower ] }}"
  when: ansible_os_family.lower().find('opensuse') != -1

- name: MySQL | Ensure MySQL is running
  service:
    name:  "{{ mysql_service_name[ ansible_os_family | lower ] }}"
    state: started
