FROM debian:jessie
MAINTAINER ANXS


# Setup system with minimum requirements + ansible
RUN apt-get update -qq && \
    apt-get install -qq python-apt python-pycurl python-pip python-dev locales sudo && \
    pip install -q ansible==1.9.4

# Copy our role into the container, using our role name
WORKDIR /tmp/mysql
COPY  .  /tmp/mysql

# Run our play
RUN echo localhost > inventory
RUN ansible-playbook -i inventory -c local --become tests/test.yml
